---
abstract: 'Module for YQL queries'
author:
  - 'Charles A. Wimmer <charles@wimmer.net>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  List::MoreUtils: 0
  Pod::Coverage::TrustPod: 0
  TAP::Formatter::JUnit: 0
  TAP::Harness::JUnit: 0
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod::Coverage: 1.08
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120530'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-YQL
requires:
  JSON::Any: 0
  LWP::UserAgent: 0
  Moose: 0
  URI: 0
  URI::QueryParam: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/cwimmer/WWW-YQL.git
version: 0.001
